
@url = http://localhost:3000/api
###

GET {{url}}/test
###

POST {{url}}/test
Content-Type:application/json

{
	"key": "hola"
}
###



// -----------------
// U S E R
// -----------------

// Register empleado

POST {{url}}/user/register
Content-Type:application/json

{
	"username": "asdf",
	"email": "asdf@labor.com",
	"password": "1234",
	"province": "Valencia",
	"city": "Valencia",
	"is_company": false,
	"name": "Ricardo",
	"surname": "Salas",
	"nif": "25774146S",
	"phone": "647009123",
	"website": "www.asd.es",
	"description": "test"
}
###



// Register empresa

POST {{url}}/user/register
Content-Type:application/json

{
	"username": "Empresa01",
	"email": "empresa01@labor.es",
	"password": "1234",
	"sector": "IT",
	"is_company": true,
	"name": "Empresa 01",
	"cif": "25774146S",
	"phone": "647009123",
	"website": "www.empresa01.es",
	"description": "Soy la empresa 01"
}
###



// Perfil de usuario

GET {{url}}/user/e5e32fa3e44383


###

POST  {{url}}/user/editProfile/e5e32fa3e44383
Content-Type:application/json

{
	"name": "Manolo",
	"surname": "El del bombo",
	"email": "Manolo@labor.es",
	"province": "Murcia",
	"city": "Gandia"
}


###



// Login
# @name resLogin

POST {{url}}/user/login
Content-Type:application/json

{
	"username":  "Icaruk",
	"password":  "1234"
}
###



@userId = {{resLogin.response.body.userId}}
@token = {{resLogin.response.body.token}}



// Logout
GET {{url}}/user/logout?token={{token}}
###

// --------------------------------
// O F E R T A  D E  T R A B A J O
// --------------------------------

// Register offer

POST {{url}}/offer/register/c5e359f46d90ee
Content-Type:application/json

{
	"title": "asdf@labor.com",
	"description": "Oferta mu wena pa currá",
	"sector": "tecnologico",
	"experience": "2",
	"min_salary":10000,
	"max_salary":20000,
	"workday":"no se que va aqui",
	"contract_type":"jc",
	"vacants":5,
	"city": "Valencia",
	"province":"Valencia",
	"promotion_level": 2,
	"is_active": 1
}
###
