
@url = http://localhost:3000/api
###

GET {{url}}/test
###

POST {{url}}/test
Content-Type:application/json

{
	"key": "hola"
}
###



// -----------------
// U S E R
// -----------------

// Register empleado

POST {{url}}/user/register
Content-Type:application/json

{
	"username": "Adrian",
	"email": "adri@labor.com",
	"password": "1234",
	"province": "Valencia",
	"city": "Castellon",
	"is_company": false,
	"name": "Adrian",
	"surname": "Tortaja",
	"nif": "257799946S",
	"phone": "647009123",
	"website": "www.asd.es",
	"description": "mi descripcion"
}
###



// Register empresa

POST {{url}}/user/register
Content-Type:application/json

{
	"username": "Empresa01",
	"email": "empresa01@labor.es",
	"password": "1234",
	"sector": "IT",
	"is_company": true,
	"name": "Empresa 01",
	"cif": "25775889S",
	"phone": "647009123",
	"website": "www.empresa01.es",
	"description": "Soy la empresa 02"
}
###

// Find companies

GET {{url}}/user/find
Content-Type:application/json

{
	"keyword": "empresa"
}
###

// Perfil de usuario

GET {{url}}/user/e5e3838776f1c2


###

POST  {{url}}/user/editProfile/e5e32fa3e44383
Content-Type:application/json

{
	"name": "Manolo",
	"surname": "El del bombo",
	"email": "Manolo@labor.es",
	"province": "Murcia",
	"city": "Gandia"
}


###



// Login
# @name resLogin

POST {{url}}/user/login
Content-Type:application/json

{
	"username":  "",
	"password":  "1234"
}
###



@uid = {{resLogin.response.body.uid}}
@token = {{resLogin.response.body.token}}



// Logout
GET {{url}}/user/logout?token={{token}}
###

// --------------------------------
// O F E R T A  D E  T R A B A J O
// --------------------------------

// Register offer

POST {{url}}/offer/register/c5e39d9c225df7
Content-Type:application/json

{
	"title": "Mamporrero",
	"contract_type": "indefinito",
	"description": "se busca amante masturbador",
	"sector": "Equino",
	"experience": "15",
	"min_salary":10,
	"max_salary":20,
	"workday":"jc",
	"vacants":5,
	"city": "Valencia",
	"province":"Valencia"
}
###
// Find offers

POST {{url}}/offer/find
Content-Type:application/json

{
	"keyword":"fach"
}
###

// Apply to an offer

POST  {{url}}/offer/apply/c5e39d9ea7a214/e5e39d9c737929
Content-Type:application/json

###

// Get applied offers

GET  {{url}}/offer/applied/e5e39d9c737929
Content-Type:application/json

###

// cancel offer
GET  {{url}}/offer/cancel/e5e39d9c737929/e5e39d9c737929
Content-Type:application/json

// --------------------------------
// S K I L L S
// --------------------------------



// Get all skills

GET  {{url}}/skill
Content-Type:application/json

// Apply to an skill

###
POST  {{url}}/skill/apply/3/e5e39d9c737929
Content-Type:application/json

###

// Get applied skills

GET  {{url}}/skill/applied/1
Content-Type:application/json

###



